# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_expert.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_expert(object):
    def setupUi(self, Add_expert):
        Add_expert.setObjectName("Add_expert")
        Add_expert.resize(400, 575)
        self.pushButton_add_expert = QtWidgets.QPushButton(Add_expert)
        self.pushButton_add_expert.setGeometry(QtCore.QRect(20, 520, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add_expert.setFont(font)
        self.pushButton_add_expert.setObjectName("pushButton_add_expert")
        self.pushButton_exit = QtWidgets.QPushButton(Add_expert)
        self.pushButton_exit.setGeometry(QtCore.QRect(280, 520, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_name_expert = QtWidgets.QLabel(Add_expert)
        self.label_name_expert.setGeometry(QtCore.QRect(20, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_name_expert.setFont(font)
        self.label_name_expert.setObjectName("label_name_expert")
        self.lineEdit_name_expert = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_name_expert.setGeometry(QtCore.QRect(150, 20, 231, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_name_expert.setFont(font)
        self.lineEdit_name_expert.setObjectName("lineEdit_name_expert")
        self.comboBox_category_expert = QtWidgets.QComboBox(Add_expert)
        self.comboBox_category_expert.setGeometry(QtCore.QRect(20, 340, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_category_expert.setFont(font)
        self.comboBox_category_expert.setObjectName("comboBox_category_expert")
        self.label_email_expert = QtWidgets.QLabel(Add_expert)
        self.label_email_expert.setGeometry(QtCore.QRect(20, 120, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_email_expert.setFont(font)
        self.label_email_expert.setObjectName("label_email_expert")
        self.label_phone_expert = QtWidgets.QLabel(Add_expert)
        self.label_phone_expert.setGeometry(QtCore.QRect(20, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_phone_expert.setFont(font)
        self.label_phone_expert.setObjectName("label_phone_expert")
        self.lineEdit_email_expert = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_email_expert.setGeometry(QtCore.QRect(100, 120, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_email_expert.setFont(font)
        self.lineEdit_email_expert.setObjectName("lineEdit_email_expert")
        self.lineEdit_phone_expert = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_phone_expert.setGeometry(QtCore.QRect(100, 90, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_phone_expert.setFont(font)
        self.lineEdit_phone_expert.setObjectName("lineEdit_phone_expert")
        self.label_position_expert = QtWidgets.QLabel(Add_expert)
        self.label_position_expert.setGeometry(QtCore.QRect(20, 180, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_position_expert.setFont(font)
        self.label_position_expert.setObjectName("label_position_expert")
        self.label_work_place_expert = QtWidgets.QLabel(Add_expert)
        self.label_work_place_expert.setGeometry(QtCore.QRect(20, 150, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_work_place_expert.setFont(font)
        self.label_work_place_expert.setObjectName("label_work_place_expert")
        self.lineEdit_position_expert = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_position_expert.setGeometry(QtCore.QRect(120, 180, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_position_expert.setFont(font)
        self.lineEdit_position_expert.setObjectName("lineEdit_position_expert")
        self.lineEdit_work_place_expert = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_work_place_expert.setGeometry(QtCore.QRect(140, 150, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_work_place_expert.setFont(font)
        self.lineEdit_work_place_expert.setObjectName("lineEdit_work_place_expert")
        self.label_expert_data = QtWidgets.QLabel(Add_expert)
        self.label_expert_data.setGeometry(QtCore.QRect(20, 60, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_expert_data.setFont(font)
        self.label_expert_data.setObjectName("label_expert_data")
        self.label_education_expert = QtWidgets.QLabel(Add_expert)
        self.label_education_expert.setGeometry(QtCore.QRect(20, 210, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_education_expert.setFont(font)
        self.label_education_expert.setObjectName("label_education_expert")
        self.lineEdit_education_expert = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_education_expert.setGeometry(QtCore.QRect(130, 210, 251, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_education_expert.setFont(font)
        self.lineEdit_education_expert.setObjectName("lineEdit_education_expert")
        self.label_academic_degree_expert = QtWidgets.QLabel(Add_expert)
        self.label_academic_degree_expert.setGeometry(QtCore.QRect(20, 240, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_academic_degree_expert.setFont(font)
        self.label_academic_degree_expert.setObjectName("label_academic_degree_expert")
        self.lineEdit_academic_degree_expert = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_academic_degree_expert.setGeometry(QtCore.QRect(150, 240, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_academic_degree_expert.setFont(font)
        self.lineEdit_academic_degree_expert.setObjectName("lineEdit_academic_degree_expert")
        self.label_academic_rank_expert = QtWidgets.QLabel(Add_expert)
        self.label_academic_rank_expert.setGeometry(QtCore.QRect(20, 270, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_academic_rank_expert.setFont(font)
        self.label_academic_rank_expert.setObjectName("label_academic_rank_expert")
        self.lineEdit_academic_rank_expert = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_academic_rank_expert.setGeometry(QtCore.QRect(150, 270, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_academic_rank_expert.setFont(font)
        self.lineEdit_academic_rank_expert.setObjectName("lineEdit_academic_rank_expert")
        self.label_category_expert = QtWidgets.QLabel(Add_expert)
        self.label_category_expert.setGeometry(QtCore.QRect(20, 310, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_category_expert.setFont(font)
        self.label_category_expert.setTextFormat(QtCore.Qt.AutoText)
        self.label_category_expert.setObjectName("label_category_expert")
        self.lineEdit_academic_rank_expert_2 = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_academic_rank_expert_2.setGeometry(QtCore.QRect(150, 420, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_academic_rank_expert_2.setFont(font)
        self.lineEdit_academic_rank_expert_2.setObjectName("lineEdit_academic_rank_expert_2")
        self.label_academic_rank_expert_2 = QtWidgets.QLabel(Add_expert)
        self.label_academic_rank_expert_2.setGeometry(QtCore.QRect(20, 390, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_academic_rank_expert_2.setFont(font)
        self.label_academic_rank_expert_2.setObjectName("label_academic_rank_expert_2")
        self.lineEdit_academic_rank_expert_3 = QtWidgets.QLineEdit(Add_expert)
        self.lineEdit_academic_rank_expert_3.setGeometry(QtCore.QRect(150, 470, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_academic_rank_expert_3.setFont(font)
        self.lineEdit_academic_rank_expert_3.setObjectName("lineEdit_academic_rank_expert_3")
        self.label_academic_rank_expert_3 = QtWidgets.QLabel(Add_expert)
        self.label_academic_rank_expert_3.setGeometry(QtCore.QRect(20, 440, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_academic_rank_expert_3.setFont(font)
        self.label_academic_rank_expert_3.setObjectName("label_academic_rank_expert_3")

        self.retranslateUi(Add_expert)
        QtCore.QMetaObject.connectSlotsByName(Add_expert)

    def retranslateUi(self, Add_expert):
        _translate = QtCore.QCoreApplication.translate
        Add_expert.setWindowTitle(_translate("Add_expert", "Добавление эксперта"))
        self.pushButton_add_expert.setText(_translate("Add_expert", "Добавить эксперта"))
        self.pushButton_exit.setText(_translate("Add_expert", "Отмена"))
        self.label_name_expert.setText(_translate("Add_expert", "ФИО эксперта:"))
        self.label_email_expert.setText(_translate("Add_expert", "E-mail:"))
        self.label_phone_expert.setText(_translate("Add_expert", "Телефон:"))
        self.label_position_expert.setText(_translate("Add_expert", "Должность:"))
        self.label_work_place_expert.setText(_translate("Add_expert", "Место работы:"))
        self.label_expert_data.setText(_translate("Add_expert", "Данные эксперта"))
        self.label_education_expert.setText(_translate("Add_expert", "Образование:"))
        self.label_academic_degree_expert.setText(_translate("Add_expert", "Ученая степень:"))
        self.label_academic_rank_expert.setText(_translate("Add_expert", "Ученое звание:"))
        self.label_category_expert.setText(_translate("Add_expert", "Степень осведомленности эксперта:"))
        self.label_academic_rank_expert_2.setText(_translate("Add_expert", "Логин для входа эксперта в систему:"))
        self.label_academic_rank_expert_3.setText(_translate("Add_expert", "Пароль для входа эксперта в систему:"))

