# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Authorization_expert.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authorization_expert(object):
    def setupUi(self, Authorization_expert):
        Authorization_expert.setObjectName("Authorization_expert")
        Authorization_expert.resize(644, 260)
        self.centralwidget = QtWidgets.QWidget(Authorization_expert)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name_expert = QtWidgets.QLabel(self.centralwidget)
        self.label_name_expert.setGeometry(QtCore.QRect(10, 70, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_name_expert.setFont(font)
        self.label_name_expert.setObjectName("label_name_expert")
        self.label_login_expert = QtWidgets.QLabel(self.centralwidget)
        self.label_login_expert.setGeometry(QtCore.QRect(10, 110, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_login_expert.setFont(font)
        self.label_login_expert.setObjectName("label_login_expert")
        self.lineEdit_login_expert = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_login_expert.setGeometry(QtCore.QRect(320, 110, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_login_expert.setFont(font)
        self.lineEdit_login_expert.setReadOnly(True)
        self.lineEdit_login_expert.setObjectName("lineEdit_login_expert")
        self.label_password_expert = QtWidgets.QLabel(self.centralwidget)
        self.label_password_expert.setGeometry(QtCore.QRect(10, 160, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_password_expert.setFont(font)
        self.label_password_expert.setObjectName("label_password_expert")
        self.lineEdit_password_expert = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password_expert.setGeometry(QtCore.QRect(320, 160, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_password_expert.setFont(font)
        self.lineEdit_password_expert.setReadOnly(True)
        self.lineEdit_password_expert.setObjectName("lineEdit_password_expert")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(10, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next.setGeometry(QtCore.QRect(440, 200, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setObjectName("pushButton_next")
        self.comboBox_select_expert = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_select_expert.setGeometry(QtCore.QRect(290, 70, 341, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.comboBox_select_expert.setFont(font)
        self.comboBox_select_expert.setObjectName("comboBox_select_expert")
        self.label_menu_expert = QtWidgets.QLabel(self.centralwidget)
        self.label_menu_expert.setGeometry(QtCore.QRect(190, 20, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_menu_expert.setFont(font)
        self.label_menu_expert.setObjectName("label_menu_expert")
        Authorization_expert.setCentralWidget(self.centralwidget)

        self.retranslateUi(Authorization_expert)
        QtCore.QMetaObject.connectSlotsByName(Authorization_expert)

    def retranslateUi(self, Authorization_expert):
        _translate = QtCore.QCoreApplication.translate
        Authorization_expert.setWindowTitle(_translate("Authorization_expert", "Авторизация эксперта"))
        self.label_name_expert.setText(_translate("Authorization_expert", "Выберите себя из списка экспертов:"))
        self.label_login_expert.setText(_translate("Authorization_expert", "Укажите Ваш логин для входа в систему:"))
        self.label_password_expert.setText(_translate("Authorization_expert", "Укажите Ваш пароль для входа в систему:"))
        self.pushButton_exit.setText(_translate("Authorization_expert", "Назад"))
        self.pushButton_next.setText(_translate("Authorization_expert", "Продолжить"))
        self.label_menu_expert.setText(_translate("Authorization_expert", "Меню авторизации эксперта"))
