# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_leader.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Leader_menu(object):
    def setupUi(self, Leader_menu):
        Leader_menu.setObjectName("Leader_menu")
        Leader_menu.resize(838, 475)
        self.centralwidget = QtWidgets.QWidget(Leader_menu)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 831, 471))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_full_description_NED = QtWidgets.QLabel(self.tab)
        self.label_full_description_NED.setGeometry(QtCore.QRect(10, 160, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_full_description_NED.setFont(font)
        self.label_full_description_NED.setObjectName("label_full_description_NED")
        self.lineEdit_name_NED = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_name_NED.setGeometry(QtCore.QRect(300, 10, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_name_NED.setFont(font)
        self.lineEdit_name_NED.setObjectName("lineEdit_name_NED")
        self.label_name_NED = QtWidgets.QLabel(self.tab)
        self.label_name_NED.setGeometry(QtCore.QRect(10, 10, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_name_NED.setFont(font)
        self.label_name_NED.setObjectName("label_name_NED")
        self.pushButton_save_main = QtWidgets.QPushButton(self.tab)
        self.pushButton_save_main.setGeometry(QtCore.QRect(600, 390, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_save_main.setFont(font)
        self.pushButton_save_main.setObjectName("pushButton_save_main")
        self.textEdit_full_description_NED = QtWidgets.QTextEdit(self.tab)
        self.textEdit_full_description_NED.setGeometry(QtCore.QRect(240, 130, 581, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textEdit_full_description_NED.setFont(font)
        self.textEdit_full_description_NED.setObjectName("textEdit_full_description_NED")
        self.label_short_name_NED = QtWidgets.QLabel(self.tab)
        self.label_short_name_NED.setGeometry(QtCore.QRect(40, 80, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_short_name_NED.setFont(font)
        self.label_short_name_NED.setObjectName("label_short_name_NED")
        self.lineEdit_short_name_NED = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_short_name_NED.setGeometry(QtCore.QRect(240, 70, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_short_name_NED.setFont(font)
        self.lineEdit_short_name_NED.setObjectName("lineEdit_short_name_NED")
        self.label_name_leader = QtWidgets.QLabel(self.tab)
        self.label_name_leader.setGeometry(QtCore.QRect(20, 300, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_name_leader.setFont(font)
        self.label_name_leader.setObjectName("label_name_leader")
        self.lineEdit_name_leader = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_name_leader.setGeometry(QtCore.QRect(200, 300, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_name_leader.setFont(font)
        self.lineEdit_name_leader.setObjectName("lineEdit_name_leader")
        self.lineEdit_phone_leader = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_phone_leader.setGeometry(QtCore.QRect(200, 340, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_phone_leader.setFont(font)
        self.lineEdit_phone_leader.setObjectName("lineEdit_phone_leader")
        self.lineEdit_email_leader = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_email_leader.setGeometry(QtCore.QRect(200, 380, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_email_leader.setFont(font)
        self.lineEdit_email_leader.setObjectName("lineEdit_email_leader")
        self.label_phone_leader = QtWidgets.QLabel(self.tab)
        self.label_phone_leader.setGeometry(QtCore.QRect(20, 340, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_phone_leader.setFont(font)
        self.label_phone_leader.setObjectName("label_phone_leader")
        self.label_email_leader = QtWidgets.QLabel(self.tab)
        self.label_email_leader.setGeometry(QtCore.QRect(20, 380, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_email_leader.setFont(font)
        self.label_email_leader.setObjectName("label_email_leader")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_save_classes = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_save_classes.setGeometry(QtCore.QRect(590, 400, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_save_classes.setFont(font)
        self.pushButton_save_classes.setObjectName("pushButton_save_classes")
        self.label_state_classes = QtWidgets.QLabel(self.tab_5)
        self.label_state_classes.setGeometry(QtCore.QRect(30, 10, 641, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_state_classes.setFont(font)
        self.label_state_classes.setObjectName("label_state_classes")
        self.tableView_list__state_classes = QtWidgets.QTableView(self.tab_5)
        self.tableView_list__state_classes.setGeometry(QtCore.QRect(10, 30, 661, 361))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableView_list__state_classes.setFont(font)
        self.tableView_list__state_classes.setObjectName("tableView_list__state_classes")
        self.pushButton_add_state_classes = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_add_state_classes.setGeometry(QtCore.QRect(680, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_add_state_classes.setFont(font)
        self.pushButton_add_state_classes.setObjectName("pushButton_add_state_classes")
        self.pushButton_delete__state_classes = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_delete__state_classes.setGeometry(QtCore.QRect(680, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_delete__state_classes.setFont(font)
        self.pushButton_delete__state_classes.setObjectName("pushButton_delete__state_classes")
        self.pushButton_edit_state_classes = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_edit_state_classes.setGeometry(QtCore.QRect(680, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_edit_state_classes.setFont(font)
        self.pushButton_edit_state_classes.setObjectName("pushButton_edit_state_classes")
        self.pushButton_redo_state_classes = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_redo_state_classes.setGeometry(QtCore.QRect(20, 400, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_redo_state_classes.setFont(font)
        self.pushButton_redo_state_classes.setObjectName("pushButton_redo_state_classes")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_category_speakers = QtWidgets.QLabel(self.tab_4)
        self.label_category_speakers.setGeometry(QtCore.QRect(30, 0, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_category_speakers.setFont(font)
        self.label_category_speakers.setObjectName("label_category_speakers")
        self.tableView_list_category_speakers = QtWidgets.QTableView(self.tab_4)
        self.tableView_list_category_speakers.setGeometry(QtCore.QRect(30, 30, 201, 361))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableView_list_category_speakers.setFont(font)
        self.tableView_list_category_speakers.setObjectName("tableView_list_category_speakers")
        self.tableView_list_subcategories_speakers = QtWidgets.QTableView(self.tab_4)
        self.tableView_list_subcategories_speakers.setGeometry(QtCore.QRect(290, 30, 511, 361))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableView_list_subcategories_speakers.setFont(font)
        self.tableView_list_subcategories_speakers.setObjectName("tableView_list_subcategories_speakers")
        self.label_list_subcategories_speakers = QtWidgets.QLabel(self.tab_4)
        self.label_list_subcategories_speakers.setGeometry(QtCore.QRect(290, 0, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_list_subcategories_speakers.setFont(font)
        self.label_list_subcategories_speakers.setObjectName("label_list_subcategories_speakers")
        self.pushButton_save_speakers = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_save_speakers.setGeometry(QtCore.QRect(590, 400, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_save_speakers.setFont(font)
        self.pushButton_save_speakers.setObjectName("pushButton_save_speakers")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_add_expert = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_add_expert.setGeometry(QtCore.QRect(680, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_add_expert.setFont(font)
        self.pushButton_add_expert.setObjectName("pushButton_add_expert")
        self.pushButton_edit_expert = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_edit_expert.setGeometry(QtCore.QRect(680, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_edit_expert.setFont(font)
        self.pushButton_edit_expert.setObjectName("pushButton_edit_expert")
        self.label_list_expert = QtWidgets.QLabel(self.tab_3)
        self.label_list_expert.setGeometry(QtCore.QRect(120, 5, 471, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_list_expert.setFont(font)
        self.label_list_expert.setObjectName("label_list_expert")
        self.pushButton_delete_expert = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_delete_expert.setGeometry(QtCore.QRect(680, 200, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_delete_expert.setFont(font)
        self.pushButton_delete_expert.setObjectName("pushButton_delete_expert")
        self.tableView_list_expert = QtWidgets.QTableView(self.tab_3)
        self.tableView_list_expert.setGeometry(QtCore.QRect(10, 30, 661, 361))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableView_list_expert.setFont(font)
        self.tableView_list_expert.setObjectName("tableView_list_expert")
        self.pushButton_save_expert = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_save_expert.setGeometry(QtCore.QRect(590, 400, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_save_expert.setFont(font)
        self.pushButton_save_expert.setObjectName("pushButton_save_expert")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_database = QtWidgets.QLabel(self.tab_2)
        self.label_database.setGeometry(QtCore.QRect(20, 20, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_database.setFont(font)
        self.label_database.setObjectName("label_database")
        self.pushButton_database_settings = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_database_settings.setGeometry(QtCore.QRect(20, 60, 511, 51))
        self.pushButton_database_settings.setObjectName("pushButton_database_settings")
        self.textEdit_database = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_database.setGeometry(QtCore.QRect(210, 20, 321, 31))
        self.textEdit_database.setObjectName("textEdit_database")
        self.pushButton_create_project = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_create_project.setGeometry(QtCore.QRect(590, 20, 211, 91))
        self.pushButton_create_project.setObjectName("pushButton_create_project")
        self.pushButton_clone_project = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_clone_project.setGeometry(QtCore.QRect(590, 130, 211, 91))
        self.pushButton_clone_project.setObjectName("pushButton_clone_project")
        self.pushButton_network_settings = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_network_settings.setGeometry(QtCore.QRect(20, 350, 211, 51))
        self.pushButton_network_settings.setObjectName("pushButton_network_settings")
        self.tabWidget.addTab(self.tab_2, "")
        Leader_menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Leader_menu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Leader_menu)

    def retranslateUi(self, Leader_menu):
        _translate = QtCore.QCoreApplication.translate
        Leader_menu.setWindowTitle(_translate("Leader_menu", "Меню для руководителя"))
        self.label_full_description_NED.setText(_translate("Leader_menu", "<html><head/><body><p align=\"center\">Подробное описание набора <br/>экспериментальных данных:</p></body></html>"))
        self.label_name_NED.setText(_translate("Leader_menu", "<html><head/><body><p align=\"center\">Название набора экспериментальных <br/>данных:</p></body></html>"))
        self.pushButton_save_main.setText(_translate("Leader_menu", "Сохранить изменения в БД"))
        self.label_short_name_NED.setText(_translate("Leader_menu", "Краткое название НЭД:"))
        self.lineEdit_short_name_NED.setText(_translate("Leader_menu", "Краткое название НЭД"))
        self.label_name_leader.setText(_translate("Leader_menu", "Руководитель проекта:"))
        self.label_phone_leader.setText(_translate("Leader_menu", "Телефон руководителя:"))
        self.label_email_leader.setText(_translate("Leader_menu", "E-mail руководителя:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Leader_menu", "Главная"))
        self.pushButton_save_classes.setText(_translate("Leader_menu", "Сохранить изменения в БД"))
        self.label_state_classes.setText(_translate("Leader_menu", "<html><head/><body><p>Классы состояний, в которых  предположительно могут находиться дикторы:</p></body></html>"))
        self.pushButton_add_state_classes.setText(_translate("Leader_menu", "Добавить"))
        self.pushButton_delete__state_classes.setText(_translate("Leader_menu", "Удалить"))
        self.pushButton_edit_state_classes.setText(_translate("Leader_menu", "Редактировать"))
        self.pushButton_redo_state_classes.setText(_translate("Leader_menu", "Обработать описания состояний, предложенные экспертами"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Leader_menu", "Классы состояний"))
        self.label_category_speakers.setText(_translate("Leader_menu", "Категории дикторов:"))
        self.label_list_subcategories_speakers.setText(_translate("Leader_menu", "Подкатегории дикторов:"))
        self.pushButton_save_speakers.setText(_translate("Leader_menu", "Сохранить изменения в БД"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Leader_menu", "Дикторы"))
        self.pushButton_add_expert.setText(_translate("Leader_menu", "Добавить"))
        self.pushButton_edit_expert.setText(_translate("Leader_menu", "Редактировать"))
        self.label_list_expert.setText(_translate("Leader_menu", "Список экспертов, привлеченных к реализации проекта:"))
        self.pushButton_delete_expert.setText(_translate("Leader_menu", "Удалить"))
        self.pushButton_save_expert.setText(_translate("Leader_menu", "Сохранить изменения в БД"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Leader_menu", "Эксперты"))
        self.label_database.setText(_translate("Leader_menu", "Текущая база данных:"))
        self.pushButton_database_settings.setText(_translate("Leader_menu", "Настроить"))
        self.pushButton_create_project.setText(_translate("Leader_menu", "Создать новый Проект"))
        self.pushButton_clone_project.setText(_translate("Leader_menu", "Клонировать Проект"))
        self.pushButton_network_settings.setText(_translate("Leader_menu", "Сетевые настройки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Leader_menu", "Настройки"))

