# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu_expert.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu_expert(object):
    def setupUi(self, Menu_expert):
        Menu_expert.setObjectName("Menu_expert")
        Menu_expert.resize(957, 670)
        self.centralwidget = QtWidgets.QWidget(Menu_expert)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 971, 661))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_add_url_YT = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_add_url_YT.setGeometry(QtCore.QRect(40, 80, 501, 20))
        self.lineEdit_add_url_YT.setObjectName("lineEdit_add_url_YT")
        self.label_select_url_YT = QtWidgets.QLabel(self.tab_3)
        self.label_select_url_YT.setGeometry(QtCore.QRect(40, 60, 421, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_url_YT.setFont(font)
        self.label_select_url_YT.setObjectName("label_select_url_YT")
        self.comboBox_select_class_YT = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_select_class_YT.setGeometry(QtCore.QRect(40, 380, 501, 22))
        self.comboBox_select_class_YT.setObjectName("comboBox_select_class_YT")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_date_download_video_YT = QtWidgets.QLabel(self.tab_3)
        self.label_date_download_video_YT.setGeometry(QtCore.QRect(40, 160, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_date_download_video_YT.setFont(font)
        self.label_date_download_video_YT.setObjectName("label_date_download_video_YT")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 0, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit_condition_download_video_YT = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_condition_download_video_YT.setGeometry(QtCore.QRect(40, 200, 501, 71))
        self.textEdit_condition_download_video_YT.setObjectName("textEdit_condition_download_video_YT")
        self.pushButton_download_video_YT = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_download_video_YT.setGeometry(QtCore.QRect(40, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_download_video_YT.setFont(font)
        self.pushButton_download_video_YT.setObjectName("pushButton_download_video_YT")
        self.pushButton_associate_video_with_class_YT = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_associate_video_with_class_YT.setGeometry(QtCore.QRect(40, 550, 451, 61))
        self.pushButton_associate_video_with_class_YT.setObjectName("pushButton_associate_video_with_class_YT")
        self.pushButton_edit_video_YT = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_edit_video_YT.setGeometry(QtCore.QRect(40, 290, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_edit_video_YT.setFont(font)
        self.pushButton_edit_video_YT.setObjectName("pushButton_edit_video_YT")
        self.label_select_speaker_YT = QtWidgets.QLabel(self.tab_3)
        self.label_select_speaker_YT.setGeometry(QtCore.QRect(40, 20, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_speaker_YT.setFont(font)
        self.label_select_speaker_YT.setObjectName("label_select_speaker_YT")
        self.textEdit_watch_video_YT = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_watch_video_YT.setGeometry(QtCore.QRect(560, 40, 391, 231))
        self.textEdit_watch_video_YT.setObjectName("textEdit_watch_video_YT")
        self.textEdit_description_state_speaker_YT = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_description_state_speaker_YT.setGeometry(QtCore.QRect(40, 430, 501, 111))
        self.textEdit_description_state_speaker_YT.setObjectName("textEdit_description_state_speaker_YT")
        self.lineEdit_date_download_video_YT = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_date_download_video_YT.setGeometry(QtCore.QRect(300, 160, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_date_download_video_YT.setFont(font)
        self.lineEdit_date_download_video_YT.setObjectName("lineEdit_date_download_video_YT")
        self.label_condition_download_video_YT = QtWidgets.QLabel(self.tab_3)
        self.label_condition_download_video_YT.setGeometry(QtCore.QRect(40, 180, 471, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_condition_download_video_YT.setFont(font)
        self.label_condition_download_video_YT.setObjectName("label_condition_download_video_YT")
        self.pushButton_use_video_YT = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_use_video_YT.setGeometry(QtCore.QRect(320, 290, 221, 41))
        self.pushButton_use_video_YT.setObjectName("pushButton_use_video_YT")
        self.label_select_class_YT = QtWidgets.QLabel(self.tab_3)
        self.label_select_class_YT.setGeometry(QtCore.QRect(40, 350, 431, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_class_YT.setFont(font)
        self.label_select_class_YT.setObjectName("label_select_class_YT")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_select_speaker_YT = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_select_speaker_YT.setGeometry(QtCore.QRect(260, 20, 281, 22))
        self.comboBox_select_speaker_YT.setObjectName("comboBox_select_speaker_YT")
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(10, 270, 931, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_description_state_speaker_YT = QtWidgets.QLabel(self.tab_3)
        self.label_description_state_speaker_YT.setGeometry(QtCore.QRect(50, 410, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_description_state_speaker_YT.setFont(font)
        self.label_description_state_speaker_YT.setObjectName("label_description_state_speaker_YT")
        self.label_watch_video_YT = QtWidgets.QLabel(self.tab_3)
        self.label_watch_video_YT.setGeometry(QtCore.QRect(580, 20, 341, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_watch_video_YT.setFont(font)
        self.label_watch_video_YT.setObjectName("label_watch_video_YT")
        self.label_watch_video_for_associate_YT = QtWidgets.QLabel(self.tab_3)
        self.label_watch_video_for_associate_YT.setGeometry(QtCore.QRect(590, 280, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_watch_video_for_associate_YT.setFont(font)
        self.label_watch_video_for_associate_YT.setObjectName("label_watch_video_for_associate_YT")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 330, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit_watch_video_for_associate_YT = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_watch_video_for_associate_YT.setGeometry(QtCore.QRect(560, 300, 391, 261))
        self.textEdit_watch_video_for_associate_YT.setObjectName("textEdit_watch_video_for_associate_YT")
        self.pushButton_aditional_class_YT = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_aditional_class_YT.setGeometry(QtCore.QRect(560, 580, 241, 41))
        self.pushButton_aditional_class_YT.setObjectName("pushButton_aditional_class_YT")
        self.pushButton_drop_YT = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_drop_YT.setGeometry(QtCore.QRect(820, 580, 131, 41))
        self.pushButton_drop_YT.setObjectName("pushButton_drop_YT")
        self.pushButton_delete_video_YT = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_delete_video_YT.setGeometry(QtCore.QRect(320, 110, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_delete_video_YT.setFont(font)
        self.pushButton_delete_video_YT.setObjectName("pushButton_delete_video_YT")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_select_speaker_disk = QtWidgets.QLabel(self.tab_6)
        self.label_select_speaker_disk.setGeometry(QtCore.QRect(40, 10, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_speaker_disk.setFont(font)
        self.label_select_speaker_disk.setObjectName("label_select_speaker_disk")
        self.label_date_download_video_disc = QtWidgets.QLabel(self.tab_6)
        self.label_date_download_video_disc.setGeometry(QtCore.QRect(40, 160, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_date_download_video_disc.setFont(font)
        self.label_date_download_video_disc.setObjectName("label_date_download_video_disc")
        self.label_watch_video_disc = QtWidgets.QLabel(self.tab_6)
        self.label_watch_video_disc.setGeometry(QtCore.QRect(560, 10, 341, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_watch_video_disc.setFont(font)
        self.label_watch_video_disc.setObjectName("label_watch_video_disc")
        self.lineEdit_direct = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_direct.setGeometry(QtCore.QRect(40, 70, 331, 20))
        self.lineEdit_direct.setObjectName("lineEdit_direct")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.textEdit_condition_download_video_disc = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_condition_download_video_disc.setGeometry(QtCore.QRect(40, 200, 491, 71))
        self.textEdit_condition_download_video_disc.setObjectName("textEdit_condition_download_video_disc")
        self.lineEdit_date_download_video_disc = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_date_download_video_disc.setGeometry(QtCore.QRect(330, 160, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_date_download_video_disc.setFont(font)
        self.lineEdit_date_download_video_disc.setObjectName("lineEdit_date_download_video_disc")
        self.pushButton_select_direct = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_select_direct.setGeometry(QtCore.QRect(390, 50, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_select_direct.setFont(font)
        self.pushButton_select_direct.setObjectName("pushButton_select_direct")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_select_direct = QtWidgets.QLabel(self.tab_6)
        self.label_select_direct.setGeometry(QtCore.QRect(40, 50, 351, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_direct.setFont(font)
        self.label_select_direct.setObjectName("label_select_direct")
        self.pushButton_download_in_system = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_download_in_system.setGeometry(QtCore.QRect(40, 110, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_download_in_system.setFont(font)
        self.pushButton_download_in_system.setObjectName("pushButton_download_in_system")
        self.comboBox_select_speaker_disk = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_select_speaker_disk.setGeometry(QtCore.QRect(260, 10, 241, 22))
        self.comboBox_select_speaker_disk.setObjectName("comboBox_select_speaker_disk")
        self.label_condition_download_video_disc = QtWidgets.QLabel(self.tab_6)
        self.label_condition_download_video_disc.setGeometry(QtCore.QRect(40, 180, 471, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_condition_download_video_disc.setFont(font)
        self.label_condition_download_video_disc.setObjectName("label_condition_download_video_disc")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(10, -10, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.textEdit_watch_video_disc = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_watch_video_disc.setGeometry(QtCore.QRect(550, 30, 401, 241))
        self.textEdit_watch_video_disc.setObjectName("textEdit_watch_video_disc")
        self.pushButton_drop_disc = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_drop_disc.setGeometry(QtCore.QRect(810, 580, 131, 41))
        self.pushButton_drop_disc.setObjectName("pushButton_drop_disc")
        self.textEdit_description_state_speaker_disc = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_description_state_speaker_disc.setGeometry(QtCore.QRect(40, 430, 501, 111))
        self.textEdit_description_state_speaker_disc.setObjectName("textEdit_description_state_speaker_disc")
        self.label_select_class_disc = QtWidgets.QLabel(self.tab_6)
        self.label_select_class_disc.setGeometry(QtCore.QRect(40, 350, 431, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_class_disc.setFont(font)
        self.label_select_class_disc.setObjectName("label_select_class_disc")
        self.label_description_state_speaker_disc = QtWidgets.QLabel(self.tab_6)
        self.label_description_state_speaker_disc.setGeometry(QtCore.QRect(50, 410, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_description_state_speaker_disc.setFont(font)
        self.label_description_state_speaker_disc.setObjectName("label_description_state_speaker_disc")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(10, 280, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.comboBox_select_class_disc = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_select_class_disc.setGeometry(QtCore.QRect(40, 380, 501, 22))
        self.comboBox_select_class_disc.setObjectName("comboBox_select_class_disc")
        self.pushButton_edit_video_disc = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_edit_video_disc.setGeometry(QtCore.QRect(40, 290, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_edit_video_disc.setFont(font)
        self.pushButton_edit_video_disc.setObjectName("pushButton_edit_video_disc")
        self.pushButton_associate_video_with_class_disc = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_associate_video_with_class_disc.setGeometry(QtCore.QRect(40, 550, 451, 61))
        self.pushButton_associate_video_with_class_disc.setObjectName("pushButton_associate_video_with_class_disc")
        self.pushButton_aditional_class_disc = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_aditional_class_disc.setGeometry(QtCore.QRect(550, 580, 241, 41))
        self.pushButton_aditional_class_disc.setObjectName("pushButton_aditional_class_disc")
        self.pushButton_use_video_disc = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_use_video_disc.setGeometry(QtCore.QRect(270, 290, 221, 41))
        self.pushButton_use_video_disc.setObjectName("pushButton_use_video_disc")
        self.textEdit_watch_video_for_associate_disc = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_watch_video_for_associate_disc.setGeometry(QtCore.QRect(550, 300, 391, 261))
        self.textEdit_watch_video_for_associate_disc.setObjectName("textEdit_watch_video_for_associate_disc")
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setGeometry(QtCore.QRect(10, 330, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.line_3 = QtWidgets.QFrame(self.tab_6)
        self.line_3.setGeometry(QtCore.QRect(0, 270, 931, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_watch_video_for_associate_disc = QtWidgets.QLabel(self.tab_6)
        self.label_watch_video_for_associate_disc.setGeometry(QtCore.QRect(580, 280, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_watch_video_for_associate_disc.setFont(font)
        self.label_watch_video_for_associate_disc.setObjectName("label_watch_video_for_associate_disc")
        self.pushButton_delete_video_disk = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_delete_video_disk.setGeometry(QtCore.QRect(320, 110, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_delete_video_disk.setFont(font)
        self.pushButton_delete_video_disk.setObjectName("pushButton_delete_video_disk")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_description_video = QtWidgets.QLabel(self.tab_11)
        self.label_description_video.setGeometry(QtCore.QRect(40, 110, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_description_video.setFont(font)
        self.label_description_video.setObjectName("label_description_video")
        self.label_watch_video_for_associate_desc = QtWidgets.QLabel(self.tab_11)
        self.label_watch_video_for_associate_desc.setGeometry(QtCore.QRect(600, 290, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_watch_video_for_associate_desc.setFont(font)
        self.label_watch_video_for_associate_desc.setObjectName("label_watch_video_for_associate_desc")
        self.label_date_download_video_desc = QtWidgets.QLabel(self.tab_11)
        self.label_date_download_video_desc.setGeometry(QtCore.QRect(40, 90, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_date_download_video_desc.setFont(font)
        self.label_date_download_video_desc.setObjectName("label_date_download_video_desc")
        self.pushButton_edit_video_desc = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_edit_video_desc.setGeometry(QtCore.QRect(40, 300, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_edit_video_desc.setFont(font)
        self.pushButton_edit_video_desc.setObjectName("pushButton_edit_video_desc")
        self.pushButton_associate_video_with_class_desc = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_associate_video_with_class_desc.setGeometry(QtCore.QRect(40, 560, 451, 61))
        self.pushButton_associate_video_with_class_desc.setObjectName("pushButton_associate_video_with_class_desc")
        self.textEdit_watch_video_desc = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_watch_video_desc.setGeometry(QtCore.QRect(630, 40, 321, 241))
        self.textEdit_watch_video_desc.setObjectName("textEdit_watch_video_desc")
        self.comboBox_select_class_desc = QtWidgets.QComboBox(self.tab_11)
        self.comboBox_select_class_desc.setGeometry(QtCore.QRect(40, 380, 501, 22))
        self.comboBox_select_class_desc.setObjectName("comboBox_select_class_desc")
        self.pushButton_use_video_desc = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_use_video_desc.setGeometry(QtCore.QRect(270, 300, 221, 41))
        self.pushButton_use_video_desc.setObjectName("pushButton_use_video_desc")
        self.label_19 = QtWidgets.QLabel(self.tab_11)
        self.label_19.setGeometry(QtCore.QRect(10, 0, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_select_video = QtWidgets.QLabel(self.tab_11)
        self.label_select_video.setGeometry(QtCore.QRect(40, 60, 331, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_video.setFont(font)
        self.label_select_video.setObjectName("label_select_video")
        self.pushButton_aditional_class_desc = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_aditional_class_desc.setGeometry(QtCore.QRect(550, 590, 241, 41))
        self.pushButton_aditional_class_desc.setObjectName("pushButton_aditional_class_desc")
        self.line_4 = QtWidgets.QFrame(self.tab_11)
        self.line_4.setGeometry(QtCore.QRect(0, 280, 931, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lineEdit_add_speaker_4 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_add_speaker_4.setGeometry(QtCore.QRect(260, 90, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lineEdit_add_speaker_4.setFont(font)
        self.lineEdit_add_speaker_4.setObjectName("lineEdit_add_speaker_4")
        self.textEdit_description_state_speaker_desc = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_description_state_speaker_desc.setGeometry(QtCore.QRect(40, 440, 501, 111))
        self.textEdit_description_state_speaker_desc.setObjectName("textEdit_description_state_speaker_desc")
        self.label_20 = QtWidgets.QLabel(self.tab_11)
        self.label_20.setGeometry(QtCore.QRect(10, 290, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_description_state_speaker_desc = QtWidgets.QLabel(self.tab_11)
        self.label_description_state_speaker_desc.setGeometry(QtCore.QRect(40, 420, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_description_state_speaker_desc.setFont(font)
        self.label_description_state_speaker_desc.setObjectName("label_description_state_speaker_desc")
        self.textEdit_watch_video_for_associate_desc = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_watch_video_for_associate_desc.setGeometry(QtCore.QRect(590, 310, 351, 261))
        self.textEdit_watch_video_for_associate_desc.setObjectName("textEdit_watch_video_for_associate_desc")
        self.label_22 = QtWidgets.QLabel(self.tab_11)
        self.label_22.setGeometry(QtCore.QRect(10, 340, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_select_speaker_desc = QtWidgets.QLabel(self.tab_11)
        self.label_select_speaker_desc.setGeometry(QtCore.QRect(40, 20, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_speaker_desc.setFont(font)
        self.label_select_speaker_desc.setObjectName("label_select_speaker_desc")
        self.label_23 = QtWidgets.QLabel(self.tab_11)
        self.label_23.setGeometry(QtCore.QRect(10, 40, 47, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_watch_video_desc = QtWidgets.QLabel(self.tab_11)
        self.label_watch_video_desc.setGeometry(QtCore.QRect(690, 10, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_watch_video_desc.setFont(font)
        self.label_watch_video_desc.setObjectName("label_watch_video_desc")
        self.comboBox_select_speaker_desc = QtWidgets.QComboBox(self.tab_11)
        self.comboBox_select_speaker_desc.setGeometry(QtCore.QRect(260, 20, 361, 22))
        self.comboBox_select_speaker_desc.setObjectName("comboBox_select_speaker_desc")
        self.label_select_class_desc = QtWidgets.QLabel(self.tab_11)
        self.label_select_class_desc.setGeometry(QtCore.QRect(40, 360, 551, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_select_class_desc.setFont(font)
        self.label_select_class_desc.setObjectName("label_select_class_desc")
        self.textEdit_description_video = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_description_video.setGeometry(QtCore.QRect(40, 130, 321, 31))
        self.textEdit_description_video.setObjectName("textEdit_description_video")
        self.pushButton_drop_all = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_drop_all.setGeometry(QtCore.QRect(810, 590, 131, 41))
        self.pushButton_drop_all.setObjectName("pushButton_drop_all")
        self.listView_select_video = QtWidgets.QListView(self.tab_11)
        self.listView_select_video.setGeometry(QtCore.QRect(370, 60, 251, 221))
        self.listView_select_video.setObjectName("listView_select_video")
        self.label_class_speaker_desc = QtWidgets.QLabel(self.tab_11)
        self.label_class_speaker_desc.setGeometry(QtCore.QRect(40, 160, 321, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_class_speaker_desc.setFont(font)
        self.label_class_speaker_desc.setObjectName("label_class_speaker_desc")
        self.textEdit_description_speaker = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_description_speaker.setGeometry(QtCore.QRect(40, 240, 321, 41))
        self.textEdit_description_speaker.setObjectName("textEdit_description_speaker")
        self.label_description_speaker = QtWidgets.QLabel(self.tab_11)
        self.label_description_speaker.setGeometry(QtCore.QRect(40, 220, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_description_speaker.setFont(font)
        self.label_description_speaker.setObjectName("label_description_speaker")
        self.textEdit_class_speaker_desc = QtWidgets.QTextEdit(self.tab_11)
        self.textEdit_class_speaker_desc.setGeometry(QtCore.QRect(40, 180, 321, 41))
        self.textEdit_class_speaker_desc.setObjectName("textEdit_class_speaker_desc")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_add_speaker = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_add_speaker.setGeometry(QtCore.QRect(790, 60, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_add_speaker.setFont(font)
        self.pushButton_add_speaker.setObjectName("pushButton_add_speaker")
        self.tableView_list_speakers = QtWidgets.QTableView(self.tab_4)
        self.tableView_list_speakers.setGeometry(QtCore.QRect(30, 40, 741, 541))
        self.tableView_list_speakers.setObjectName("tableView_list_speakers")
        self.pushButton_edit_speaker = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_edit_speaker.setGeometry(QtCore.QRect(790, 160, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_edit_speaker.setFont(font)
        self.pushButton_edit_speaker.setObjectName("pushButton_edit_speaker")
        self.pushButton_delete_speaker = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_delete_speaker.setGeometry(QtCore.QRect(790, 260, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_delete_speaker.setFont(font)
        self.pushButton_delete_speaker.setObjectName("pushButton_delete_speaker")
        self.pushButton_inactive_speaker = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_inactive_speaker.setGeometry(QtCore.QRect(790, 360, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_inactive_speaker.setFont(font)
        self.pushButton_inactive_speaker.setObjectName("pushButton_inactive_speaker")
        self.pushButton_save_speakers = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_save_speakers.setGeometry(QtCore.QRect(730, 590, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_save_speakers.setFont(font)
        self.pushButton_save_speakers.setObjectName("pushButton_save_speakers")
        self.label_list_speakers = QtWidgets.QLabel(self.tab_4)
        self.label_list_speakers.setGeometry(QtCore.QRect(180, 10, 341, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_list_speakers.setFont(font)
        self.label_list_speakers.setObjectName("label_list_speakers")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lineEdit_path_to_save_video = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_path_to_save_video.setGeometry(QtCore.QRect(60, 70, 711, 31))
        self.lineEdit_path_to_save_video.setObjectName("lineEdit_path_to_save_video")
        self.pushButton_path_to_save_video = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_path_to_save_video.setGeometry(QtCore.QRect(780, 50, 111, 51))
        self.pushButton_path_to_save_video.setObjectName("pushButton_path_to_save_video")
        self.label_path_expert_save_video = QtWidgets.QLabel(self.tab_5)
        self.label_path_expert_save_video.setGeometry(QtCore.QRect(20, 10, 481, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_path_expert_save_video.setFont(font)
        self.label_path_expert_save_video.setObjectName("label_path_expert_save_video")
        self.label_path_to_save_video = QtWidgets.QLabel(self.tab_5)
        self.label_path_to_save_video.setGeometry(QtCore.QRect(40, 40, 741, 20))
        self.label_path_to_save_video.setObjectName("label_path_to_save_video")
        self.lineEdit_path_to_save_edit_video = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_path_to_save_edit_video.setGeometry(QtCore.QRect(60, 140, 711, 31))
        self.lineEdit_path_to_save_edit_video.setObjectName("lineEdit_path_to_save_edit_video")
        self.label_path_to_save_edit_video = QtWidgets.QLabel(self.tab_5)
        self.label_path_to_save_edit_video.setGeometry(QtCore.QRect(40, 110, 681, 20))
        self.label_path_to_save_edit_video.setObjectName("label_path_to_save_edit_video")
        self.pushButton_path_to_save_edit_vide = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_path_to_save_edit_vide.setGeometry(QtCore.QRect(780, 120, 111, 51))
        self.pushButton_path_to_save_edit_vide.setObjectName("pushButton_path_to_save_edit_vide")
        self.radioButton_local = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_local.setGeometry(QtCore.QRect(20, 420, 181, 17))
        self.radioButton_local.setObjectName("radioButton_local")
        self.radioButton_network = QtWidgets.QRadioButton(self.tab_5)
        self.radioButton_network.setGeometry(QtCore.QRect(20, 450, 161, 17))
        self.radioButton_network.setObjectName("radioButton_network")
        self.lineEdit_path_to_save_audio = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_path_to_save_audio.setGeometry(QtCore.QRect(60, 220, 711, 31))
        self.lineEdit_path_to_save_audio.setObjectName("lineEdit_path_to_save_audio")
        self.label_path_to_save_audio = QtWidgets.QLabel(self.tab_5)
        self.label_path_to_save_audio.setGeometry(QtCore.QRect(40, 190, 681, 20))
        self.label_path_to_save_audio.setObjectName("label_path_to_save_audio")
        self.pushButton_path_to_save_audio = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_path_to_save_audio.setGeometry(QtCore.QRect(780, 200, 111, 51))
        self.pushButton_path_to_save_audio.setObjectName("pushButton_path_to_save_audio")
        self.label_type_of_work = QtWidgets.QLabel(self.tab_5)
        self.label_type_of_work.setGeometry(QtCore.QRect(20, 390, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_type_of_work.setFont(font)
        self.label_type_of_work.setObjectName("label_type_of_work")
        self.label_settings_database = QtWidgets.QLabel(self.tab_5)
        self.label_settings_database.setGeometry(QtCore.QRect(20, 360, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_settings_database.setFont(font)
        self.label_settings_database.setObjectName("label_settings_database")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidget_2.setGeometry(QtCore.QRect(220, 360, 651, 261))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_settings_database_local = QtWidgets.QPushButton(self.tab)
        self.pushButton_settings_database_local.setGeometry(QtCore.QRect(410, 30, 231, 51))
        self.pushButton_settings_database_local.setObjectName("pushButton_settings_database_local")
        self.label_current_database_local = QtWidgets.QLabel(self.tab)
        self.label_current_database_local.setGeometry(QtCore.QRect(20, 10, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_current_database_local.setFont(font)
        self.label_current_database_local.setObjectName("label_current_database_local")
        self.textEdit_current_database_local = QtWidgets.QTextEdit(self.tab)
        self.textEdit_current_database_local.setGeometry(QtCore.QRect(20, 30, 371, 31))
        self.textEdit_current_database_local.setObjectName("textEdit_current_database_local")
        self.lineEdit_path_to_database = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_path_to_database.setGeometry(QtCore.QRect(20, 120, 481, 31))
        self.lineEdit_path_to_database.setObjectName("lineEdit_path_to_database")
        self.label_path_to_database = QtWidgets.QLabel(self.tab)
        self.label_path_to_database.setGeometry(QtCore.QRect(20, 90, 621, 20))
        self.label_path_to_database.setObjectName("label_path_to_database")
        self.pushButton_path_to_database = QtWidgets.QPushButton(self.tab)
        self.pushButton_path_to_database.setGeometry(QtCore.QRect(530, 110, 111, 51))
        self.pushButton_path_to_database.setObjectName("pushButton_path_to_database")
        self.pushButton_save_local_settings = QtWidgets.QPushButton(self.tab)
        self.pushButton_save_local_settings.setGeometry(QtCore.QRect(190, 190, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_save_local_settings.setFont(font)
        self.pushButton_save_local_settings.setObjectName("pushButton_save_local_settings")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_network_settings = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_network_settings.setGeometry(QtCore.QRect(420, 30, 211, 51))
        self.pushButton_network_settings.setObjectName("pushButton_network_settings")
        self.pushButton_download_from_server = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_download_from_server.setGeometry(QtCore.QRect(20, 10, 241, 51))
        self.pushButton_download_from_server.setObjectName("pushButton_download_from_server")
        self.pushButton_sync_up = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_sync_up.setGeometry(QtCore.QRect(20, 80, 311, 51))
        self.pushButton_sync_up.setObjectName("pushButton_sync_up")
        self.pushButton_load_to_server = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_load_to_server.setGeometry(QtCore.QRect(20, 150, 241, 51))
        self.pushButton_load_to_server.setObjectName("pushButton_load_to_server")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.label_name_NED = QtWidgets.QLabel(self.tab_5)
        self.label_name_NED.setGeometry(QtCore.QRect(20, 280, 501, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_NED.setFont(font)
        self.label_name_NED.setObjectName("label_name_NED")
        self.lineEdit_name_NED = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_name_NED.setGeometry(QtCore.QRect(530, 280, 141, 31))
        self.lineEdit_name_NED.setObjectName("lineEdit_name_NED")
        self.pushButton_NED_info = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_NED_info.setGeometry(QtCore.QRect(680, 280, 211, 51))
        self.pushButton_NED_info.setObjectName("pushButton_NED_info")
        self.line_2 = QtWidgets.QFrame(self.tab_5)
        self.line_2.setGeometry(QtCore.QRect(20, 260, 881, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_5 = QtWidgets.QFrame(self.tab_5)
        self.line_5.setGeometry(QtCore.QRect(30, 330, 871, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.tabWidget.addTab(self.tab_5, "")
        Menu_expert.setCentralWidget(self.centralwidget)

        self.retranslateUi(Menu_expert)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Menu_expert)

    def retranslateUi(self, Menu_expert):
        _translate = QtCore.QCoreApplication.translate
        Menu_expert.setWindowTitle(_translate("Menu_expert", "Меню эксперта"))
        self.label_4.setText(_translate("Menu_expert", "4."))
        self.lineEdit_add_url_YT.setText(_translate("Menu_expert", "URL"))
        self.label_select_url_YT.setText(_translate("Menu_expert", "Вставьте ссылку для скачивания видео с YouTube:"))
        self.label_3.setText(_translate("Menu_expert", "3."))
        self.label_date_download_video_YT.setText(_translate("Menu_expert", "Дата создания скачанного видео:"))
        self.label.setText(_translate("Menu_expert", "1."))
        self.pushButton_download_video_YT.setText(_translate("Menu_expert", "Скачать видео"))
        self.pushButton_associate_video_with_class_YT.setText(_translate("Menu_expert", "Ассоциировать [видео+описание] с выбранным диктором"))
        self.pushButton_edit_video_YT.setText(_translate("Menu_expert", "Редактировать видео"))
        self.label_select_speaker_YT.setText(_translate("Menu_expert", "Выберите диктора из списка:"))
        self.textEdit_watch_video_YT.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Предварительный просмотр скачанного (!) и записанного на компьютер эксперта видео</span></p></body></html>"))
        self.textEdit_description_state_speaker_YT.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Вербальное описание сосояния диктора на указанном фрагменте</span></p></body></html>"))
        self.lineEdit_date_download_video_YT.setText(_translate("Menu_expert", "12.12.2020"))
        self.label_condition_download_video_YT.setText(_translate("Menu_expert", "Обстоятельства, при которых скачанное видео было записано:"))
        self.pushButton_use_video_YT.setText(_translate("Menu_expert", "Использовать \"как есть\""))
        self.label_select_class_YT.setText(_translate("Menu_expert", "В каком стандартном классе состояний находится диктор:"))
        self.label_2.setText(_translate("Menu_expert", "2."))
        self.label_5.setText(_translate("Menu_expert", "5."))
        self.label_description_state_speaker_YT.setText(_translate("Menu_expert", "Описание состояния диктора:"))
        self.label_watch_video_YT.setText(_translate("Menu_expert", "Просмотр текущего загруженного видео"))
        self.label_watch_video_for_associate_YT.setText(_translate("Menu_expert", "Просмотр видео для ассоциации с диктором"))
        self.label_6.setText(_translate("Menu_expert", "6."))
        self.textEdit_watch_video_for_associate_YT.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Предварительный просмотр отредактированного экспертом видео</span></p></body></html>"))
        self.pushButton_aditional_class_YT.setText(_translate("Menu_expert", "Доп.класс.признаки"))
        self.pushButton_drop_YT.setText(_translate("Menu_expert", "Сбросить п.5,6"))
        self.pushButton_delete_video_YT.setText(_translate("Menu_expert", "Удалить загруженное видео"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Menu_expert", "Загрузка видео с YouTube"))
        self.label_13.setText(_translate("Menu_expert", "3."))
        self.label_select_speaker_disk.setText(_translate("Menu_expert", "Выберите диктора из списка:"))
        self.label_date_download_video_disc.setText(_translate("Menu_expert", "Дата создания загруженного видео:"))
        self.label_watch_video_disc.setText(_translate("Menu_expert", "Просмотр текущего загруженного видео"))
        self.lineEdit_direct.setText(_translate("Menu_expert", "Путь с расположением видео"))
        self.label_15.setText(_translate("Menu_expert", "4."))
        self.lineEdit_date_download_video_disc.setText(_translate("Menu_expert", "12.12.2020"))
        self.pushButton_select_direct.setText(_translate("Menu_expert", "Выбрать путь"))
        self.label_16.setText(_translate("Menu_expert", "2."))
        self.label_select_direct.setText(_translate("Menu_expert", "Укажите расположение файла с видеозаписью:"))
        self.pushButton_download_in_system.setText(_translate("Menu_expert", "Загрузить видео в систему"))
        self.label_condition_download_video_disc.setText(_translate("Menu_expert", "Обстоятельства, при которых загруженное видео было записано:"))
        self.label_18.setText(_translate("Menu_expert", "1."))
        self.textEdit_watch_video_disc.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Предварительный просмотр скачанного (!) и записанного на компьютер эксперта видео</span></p></body></html>"))
        self.pushButton_drop_disc.setText(_translate("Menu_expert", "Сбросить п.5,6"))
        self.textEdit_description_state_speaker_disc.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Вербальное описание сосояния диктора на указанном фрагменте</span></p></body></html>"))
        self.label_select_class_disc.setText(_translate("Menu_expert", "В каком стандартном классе состояний находится диктор:"))
        self.label_description_state_speaker_disc.setText(_translate("Menu_expert", "Описание состояния диктора:"))
        self.label_14.setText(_translate("Menu_expert", "5."))
        self.pushButton_edit_video_disc.setText(_translate("Menu_expert", "Редактировать видео"))
        self.pushButton_associate_video_with_class_disc.setText(_translate("Menu_expert", "Ассоциировать [видео+описание] с выбранным диктором"))
        self.pushButton_aditional_class_disc.setText(_translate("Menu_expert", "Доп.класс.признаки"))
        self.pushButton_use_video_disc.setText(_translate("Menu_expert", "Использовать \"как есть\""))
        self.textEdit_watch_video_for_associate_disc.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Предварительный просмотр отредактированного экспертом видео</span></p></body></html>"))
        self.label_17.setText(_translate("Menu_expert", "6."))
        self.label_watch_video_for_associate_disc.setText(_translate("Menu_expert", "Просмотр видео для ассоциации с диктором"))
        self.pushButton_delete_video_disk.setText(_translate("Menu_expert", "Удалить загруженное видео"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Menu_expert", "Загрузка видео с диска"))
        self.label_description_video.setText(_translate("Menu_expert", "Описание видеозаписи:"))
        self.label_watch_video_for_associate_desc.setText(_translate("Menu_expert", "Просмотр видео для ассоциации с диктором"))
        self.label_date_download_video_desc.setText(_translate("Menu_expert", "Дата создания видеозаписи:"))
        self.pushButton_edit_video_desc.setText(_translate("Menu_expert", "Редактировать видео"))
        self.pushButton_associate_video_with_class_desc.setText(_translate("Menu_expert", "Ассоциировать [видео+описание] с выбранным диктором"))
        self.textEdit_watch_video_desc.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Предварительный просмотр скачанного (!) и записанного на компьютер эксперта видео</span></p></body></html>"))
        self.pushButton_use_video_desc.setText(_translate("Menu_expert", "Использовать \"как есть\""))
        self.label_19.setText(_translate("Menu_expert", "1."))
        self.label_select_video.setText(_translate("Menu_expert", "Выберите видеозапись диктора для работы:"))
        self.pushButton_aditional_class_desc.setText(_translate("Menu_expert", "Доп.класс.признаки"))
        self.lineEdit_add_speaker_4.setText(_translate("Menu_expert", "12.12.2020"))
        self.textEdit_description_state_speaker_desc.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Вербальное описание сосояния диктора на указанном фрагменте</span></p></body></html>"))
        self.label_20.setText(_translate("Menu_expert", "5."))
        self.label_description_state_speaker_desc.setText(_translate("Menu_expert", "Новое Описание состояния диктора:"))
        self.textEdit_watch_video_for_associate_desc.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Предварительный просмотр отредактированного экспертом видео</span></p></body></html>"))
        self.label_22.setText(_translate("Menu_expert", "6."))
        self.label_select_speaker_desc.setText(_translate("Menu_expert", "Выберите диктора из списка:"))
        self.label_23.setText(_translate("Menu_expert", "2."))
        self.label_watch_video_desc.setText(_translate("Menu_expert", "Просмотр текущего видео"))
        self.label_select_class_desc.setText(_translate("Menu_expert", "Новое описание: В каком стандартном классе состояний находится диктор:"))
        self.pushButton_drop_all.setText(_translate("Menu_expert", "Сбросить все !"))
        self.label_class_speaker_desc.setText(_translate("Menu_expert", "Класс состояния диктора на записи:"))
        self.textEdit_description_speaker.setHtml(_translate("Menu_expert", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Вербальное описание сосояния диктора на записи</span></p></body></html>"))
        self.label_description_speaker.setText(_translate("Menu_expert", "Описание состояния диктора:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("Menu_expert", "Описание загруженного видео"))
        self.pushButton_add_speaker.setText(_translate("Menu_expert", "Добавить"))
        self.pushButton_edit_speaker.setText(_translate("Menu_expert", "Редактировать"))
        self.pushButton_delete_speaker.setText(_translate("Menu_expert", "Удалить"))
        self.pushButton_inactive_speaker.setText(_translate("Menu_expert", "Не активен !"))
        self.pushButton_save_speakers.setText(_translate("Menu_expert", "Сохранить изменения в БД"))
        self.label_list_speakers.setText(_translate("Menu_expert", "Список дикторов, внесенных в систему:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Menu_expert", "Дикторы"))
        self.lineEdit_path_to_save_video.setText(_translate("Menu_expert", "Для хранения видеозаписей, загруженных в систему из Интернета"))
        self.pushButton_path_to_save_video.setText(_translate("Menu_expert", "Выбрать"))
        self.label_path_expert_save_video.setText(_translate("Menu_expert", "Расположение на компьютере эксперта системных папок:"))
        self.label_path_to_save_video.setText(_translate("Menu_expert", "1. Для хранения видеозаписей, загруженных экспертом в систему из Интернета или самостоятельно:"))
        self.lineEdit_path_to_save_edit_video.setText(_translate("Menu_expert", "для хранения отредактированного видео, ассоциациированного с диктором"))
        self.label_path_to_save_edit_video.setText(_translate("Menu_expert", "2. Для хранения видеозаписей, ассоцированных с состоянием диктора:"))
        self.pushButton_path_to_save_edit_vide.setText(_translate("Menu_expert", "Выбрать"))
        self.radioButton_local.setText(_translate("Menu_expert", "Автономная работа"))
        self.radioButton_network.setText(_translate("Menu_expert", "Работа по сети"))
        self.lineEdit_path_to_save_audio.setText(_translate("Menu_expert", "для хранения аудиофайлов, ассоциированных с диктором"))
        self.label_path_to_save_audio.setText(_translate("Menu_expert", "3. Для размещения аудиофайлов:"))
        self.pushButton_path_to_save_audio.setText(_translate("Menu_expert", "Выбрать"))
        self.label_type_of_work.setText(_translate("Menu_expert", "Вид работы:"))
        self.label_settings_database.setText(_translate("Menu_expert", "Настройки баз данных:"))
        self.pushButton_settings_database_local.setText(_translate("Menu_expert", "Настройки БД"))
        self.label_current_database_local.setText(_translate("Menu_expert", "Текущая база данных:"))
        self.lineEdit_path_to_database.setText(_translate("Menu_expert", "Расположение базы данных"))
        self.label_path_to_database.setText(_translate("Menu_expert", "Папка на локальном компьютере, в котором размещена база данных текущего НЭД:"))
        self.pushButton_path_to_database.setText(_translate("Menu_expert", "Выбрать"))
        self.pushButton_save_local_settings.setText(_translate("Menu_expert", "Сохранить изменения в БД"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Menu_expert", "Работа на локальном компьютере"))
        self.pushButton_network_settings.setText(_translate("Menu_expert", "Сетевые настройки"))
        self.pushButton_download_from_server.setText(_translate("Menu_expert", "Загрузить данные С сервера"))
        self.pushButton_sync_up.setText(_translate("Menu_expert", "Синхронизироваться с сервером"))
        self.pushButton_load_to_server.setText(_translate("Menu_expert", "Загрузить данные НА сервер"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Menu_expert", "Работа по сети"))
        self.label_name_NED.setText(_translate("Menu_expert", "Название текущего набора экспериментальных данных (НЭД):"))
        self.lineEdit_name_NED.setText(_translate("Menu_expert", "Краткое название"))
        self.pushButton_NED_info.setText(_translate("Menu_expert", "Подробнее о текщем НЭД"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Menu_expert", "Настройки"))


